# Generated by Django 3.2 on 2021-05-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210514_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDCat', models.CharField(max_length=30, verbose_name='Categorie name')),
                ('PRDCat_img', models.ImageField(upload_to='categories', verbose_name='Categorie image')),
                ('PRDCat_Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prdcategorie')),
            ],
        ),
    ]
