# Generated by Django 3.2 on 2021-05-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_prdcategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRD_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDAlternative', models.ManyToManyField(related_name='Alternatives_products', to='product.product')),
                ('PRDSlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='selected product')),
            ],
        ),
        migrations.CreateModel(
            name='PRD_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDCat', models.CharField(max_length=30, verbose_name='Categorie name')),
                ('PRDCat_img', models.ImageField(upload_to='categories', verbose_name='Categorie image')),
                ('PRDCat_Parent', models.ForeignKey(blank=True, limit_choices_to={'PRDCat_Parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prd_cat')),
            ],
        ),
        migrations.RenameModel(
            old_name='PRDImages',
            new_name='PRD_Img',
        ),
        migrations.RenameField(
            model_name='prd_img',
            old_name='PRDImage',
            new_name='PRDImg',
        ),
        migrations.DeleteModel(
            name='PRDCategorie',
        ),
    ]
