# Generated by Django 3.2 on 2021-05-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0004_auto_20210515_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prd_alternative',
            options={'verbose_name': 'Products Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.AlterModelOptions(
            name='prd_cat',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='prd_img',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='PRDBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prd_cat'),
        ),
        migrations.AlterField(
            model_name='prd_alternative',
            name='PRDAlternative',
            field=models.ManyToManyField(related_name='Alternatives_products', to='product.product', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='prd_cat',
            name='PRDCat_Parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'PRDCat_Parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prd_cat', verbose_name='main category'),
        ),
        migrations.CreateModel(
            name='PRD_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APRDAlternatives', models.ManyToManyField(related_name='Accessories_products', to='product.product', verbose_name='Accessories')),
                ('APRDSlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='selected product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
