# Generated by Django 3.2 on 2021-05-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_prd_cat_prdcat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImg',
            field=models.ImageField(null='product/buy-1.jpg', upload_to='products/'),
            preserve_default='product/buy-1.jpg',
        ),
    ]
