# Generated by Django 3.2 on 2021-05-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_prdimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prd_cat',
            name='PRDCat_Parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'PRDCat_Parent__isnull : True'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prd_cat', verbose_name='main category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PRDCategory', to='product.prd_cat'),
        ),
    ]
