# Generated by Django 3.2 on 2021-05-19 01:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210519_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='DLDesc',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='DLimg',
        ),
        migrations.AddField(
            model_name='deal',
            name='DlImg',
            field=models.ImageField(default='default/default.jpg', upload_to='deals/', verbose_name='Deal Image'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='DLName',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDesc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description'),
        ),
    ]
