# Generated by Django 3.2 on 2021-05-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210519_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='DLName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
