# Generated by Django 3.2 on 2021-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_deal_dlname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='DlImg',
            field=models.ImageField(blank=True, null=True, upload_to='deals/', verbose_name='Deal Image'),
        ),
    ]
