# Generated by Django 3.2 on 2021-05-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210519_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Product Cost'),
        ),
    ]
