# Generated by Django 3.2 on 2021-05-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_intaimg_collection_cltimg'),
        ('product', '0015_alter_product_prdcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isinstock',
            field=models.BooleanField(default=True, verbose_name='is in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name="product's Brand"),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDImg',
            field=models.ImageField(null='product/buy-1.jpg', upload_to='products/', verbose_name="product's image"),
        ),
    ]
