# Generated by Django 3.2 on 2021-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210520_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDALT',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_product_PRDALT_+', to='product.product', verbose_name='Alternatives'),
        ),
    ]
