# Generated by Django 3.2 on 2021-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_prd_img_prdimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDALT',
            field=models.ManyToManyField(related_name='_product_product_PRDALT_+', to='product.product', verbose_name='Alternatives'),
        ),
    ]
