# Generated by Django 3.2 on 2021-05-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210520_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.IntegerField(verbose_name='Product Price'),
        ),
    ]
