# Generated by Django 3.2 on 2021-06-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_prdprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDCreated',
        ),
    ]
