# Generated by Django 3.2 on 2021-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='Fullname',
            field=models.CharField(default='costumer.fullname', max_length=30),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='Order_Comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
