# Generated by Django 3.2 on 2021-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_shippingadress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='isDefault',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
