# Generated by Django 3.2 on 2021-07-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_prdfvt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdfvt',
            name='favorites',
            field=models.ManyToManyField(related_name='facorites', to='product.product', verbose_name='favorites'),
        ),
    ]
