# Generated by Django 3.2 on 2021-07-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_prdfvt_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdfvt',
            name='favorites',
        ),
        migrations.AddField(
            model_name='prdfvt',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='prdrvd',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
