# Generated by Django 3.2 on 2021-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_intaimg_collection_cltimg'),
        ('product', '0033_orders_paiment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDBrand',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDBrand',
            field=models.ManyToManyField(blank=True, null=True, to='settings.brand', verbose_name="product's Brand"),
        ),
    ]
