# Generated by Django 3.2 on 2021-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_intaimg_collection_cltimg'),
        ('product', '0034_auto_20210711_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDBrand',
            field=models.ManyToManyField(blank=True, null=True, to='settings.Variant', verbose_name="product's Variant"),
        ),
    ]
