# Generated by Django 3.2 on 2021-07-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_intaimg_collection_cltimg'),
        ('product', '0035_alter_product_prdbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.variant'),
        ),
    ]
