# Generated by Django 3.2 on 2021-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_intaimg_collection_cltimg'),
        ('product', '0036_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDVariant',
            field=models.ManyToManyField(blank=True, null=True, to='settings.Variant', verbose_name="product's Variant"),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDBrand',
            field=models.ManyToManyField(blank=True, null=True, to='settings.brand', verbose_name="product's Brand"),
        ),
    ]
