# Generated by Django 3.2 on 2021-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20210714_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivred',
            field=models.BooleanField(default=False),
        ),
    ]
