# Generated by Django 3.2 on 2021-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_orders_delivred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDACSS',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_product_PRDACSS_+', to='product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDALT',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_product_PRDALT_+', to='product.product', verbose_name='Alternatives'),
        ),
    ]
