# Generated by Django 3.2 on 2021-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211223_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestcostumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='device_id')),
                ('email_costumer', models.CharField(max_length=30, verbose_name='costumer email')),
            ],
        ),
    ]
