# Generated by Django 3.2 on 2021-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Email_text',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
