# Generated by Django 3.2 on 2021-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='imgurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
