# Generated by Django 3.2 on 2021-12-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211217_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='imgurl',
            new_name='image_url',
        ),
    ]
