# Generated by Django 3.2 on 2021-12-22 19:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=30, verbose_name='Product Name')),
                ('PRDDesc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Price')),
                ('PRDCost', models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Product Cost')),
                ('PRDImg', models.ImageField(null='product/buy-1.jpg', upload_to='products/', verbose_name="product's image")),
                ('isinstock', models.BooleanField(default=True, verbose_name='is in stock')),
                ('PRDACSS', models.ManyToManyField(blank=True, null=True, related_name='_index_product_PRDACSS_+', to='index.product', verbose_name='Accessories')),
                ('PRDALT', models.ManyToManyField(blank=True, null=True, related_name='_index_product_PRDALT_+', to='index.product', verbose_name='Alternatives')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
