# Generated by Django 3.2 on 2021-12-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VRTtitle', models.CharField(max_length=40, verbose_name='variant')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDACSS',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, related_name='variant', to='index.Variant', verbose_name='variant'),
        ),
    ]
