# Generated by Django 3.2 on 2021-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INTAName', models.CharField(max_length=15, verbose_name='Ad name')),
                ('INTADate', models.TextField(blank=True, null=True, verbose_name='Added at:')),
                ('INTAImg', models.ImageField(blank=True, null=True, upload_to='Ads_images/')),
            ],
            options={
                'verbose_name': 'intern Ad',
                'verbose_name_plural': 'intern Ads',
            },
        ),
    ]
