# Generated by Django 3.2 on 2021-05-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='INTAImg',
            new_name='CLTImg',
        ),
    ]
