# Generated by Django 3.2 on 2022-02-22 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220217_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='DateRes',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 15, 35, 49, 194593)),
        ),
    ]
