# Generated by Django 3.2 on 2022-03-10 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220310_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='Eemail',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='DateRes',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 16, 29, 38, 194731)),
        ),
    ]
