# Generated by Django 3.2 on 2022-03-28 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_reservation_dateres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='DateRes',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 11, 7, 16, 226099)),
        ),
    ]
